name: agent-monitoring

services:
  agent-lab:
    build:
      context: .
    image: agent-lab:latest
    container_name: agent-lab
    ports:
      - "20022:20022"
      - "15034:15034"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      AGENT_HOME: /home/agent-admin/agent-app
      AGENT_PORT: "15034"
      AGENT_UPLOAD_DIR: /home/agent-admin/agent-app/upload_files
      AGENT_KEY_PATH: /home/agent-admin/agent-app/api_keys
      AGENT_LOG_DIR: /var/log/agent-app
      AGENT_PROCESS_PATTERN: agent-app|agent_app.py
    stdin_open: true
    tty: true
